### ISSUE TITLE
[P16 sover] Example fails to find valid partition with P16 solver

### ISSUE THREAD

**Issue by hemantdwave** [dwave-examples/graph-partitioning#2]
Environment:- TEST
browser:-Chrome81

Componant:-Qubist
version:-

Steps:-
1.Navigate to https://test.se.dwavesystems.com/leap/signup/ 
2. Enter all required fields 
3. Verify that user get signup activation link
4. Login
5. Navigate to IDE examples
6. open graph partition example in IDE
7. Update environment variable to use P16 solver
8. Verify if example finds valid partition
Expected:- Example should find valid partition independent of solver
Actual:-User gets error
'VALID PARTITION FOUND' not found in "B'GRAPH ON 40 NODES CREATED WITH 161 OUT OF 780.0 POSSIBLE EDGES.\\NINVALID PARTITION.\\N'"

**Comment by hemantdwave** [comment]
Passed today when ran locally will continue to monitor if it is consistent
![Screenshot from 2020-06-19 11-54-53](https://user-images.githubusercontent.com/61433992/85186319-2c14ad80-b24d-11ea-8ab6-ef21df9ddbf8.png)
![Screenshot from 2020-06-19 11-56-16](https://user-images.githubusercontent.com/61433992/85186321-2d45da80-b24d-11ea-9636-ea156e842b3c.png)

**Comment by vgoliber** [comment]
@hemantdwave do you have an update on this?

**Comment by hemantdwave** [comment]
haven't seen failure on P16 so closing this. will create new issue if found again.
